language: node_js
node_js:
  - "0.12.7"

sudo: false

before_install:
  - npm config set spin false
  - npm install -g npm@^2
  - npm install -g bower

install:
  - cd kujira
  - npm install -g phantomjs-prebuilt
  - npm install
  - bower install
  
script:
  - ember test